#!/usr/bin/env bash
# Register a PoC operator + client_credentials client via L3, then write local env (gitignored).
# Follows L3 tutorial 2-1 / 2-2 (operator → client → secret → token with operator_id).
# Does NOT print secrets to stdout (only paths / non-secret ids).
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/../../.." && pwd)"
OUT_DIR="${RATIO_ODS_ENV_DIR:-$ROOT/poc/scripts/ods/.local}"
OUT_ENV="$OUT_DIR/operator.env"

L3_URL="${RATIO_ODS_L3_URL:-http://127.0.0.1:8080}"
API_KEY="${RATIO_ODS_API_KEY:-API-Key-Sample}"
SYSTEM_CLIENT_ID="${RATIO_ODS_SYSTEM_CLIENT_ID:-system-auth-sample}"
SYSTEM_CLIENT_SECRET="${RATIO_ODS_CLIENT_SECRET:-}"

if [[ -z "$SYSTEM_CLIENT_SECRET" ]]; then
  # Prefer secret from SDK l3 compose if present
  COMPOSE="${RATIO_ODS_SDK_DIR:-$HOME/work/open-dataspaces/SDK-docker-compose}/l3/docker-compose.yml"
  if [[ -f "$COMPOSE" ]]; then
    SYSTEM_CLIENT_SECRET="$(python3 - "$COMPOSE" <<'PY'
import re, sys
text = open(sys.argv[1], encoding="utf-8").read()
m = re.search(r"KEYCLOAK_CREDENTIALS_TOKEN_INTROSPECT_CLIENT_SECRET:\s*(\S+)", text)
print(m.group(1) if m else "")
PY
)"
  fi
fi
if [[ -z "$SYSTEM_CLIENT_SECRET" ]]; then
  echo "FAIL: set RATIO_ODS_CLIENT_SECRET (system-auth-sample) or RATIO_ODS_SDK_DIR" >&2
  exit 1
fi

SUFFIX="${RATIO_ODS_OPERATOR_SUFFIX:-$(date +%s)}"
LOGIN_USER_ID="${RATIO_ODS_LOGIN_USER_ID:-ratio-poc-$SUFFIX}"
CLIENT_ID="${RATIO_ODS_OPERATOR_CLIENT_ID:-ratio-poc-client-$SUFFIX}"
OPEN_OPERATOR_ID="${RATIO_ODS_OPEN_OPERATOR_ID:-1234567890$(printf '%03d' $((SUFFIX % 1000)))}"

mkdir -p "$OUT_DIR"

echo "Fetching system access token…" >&2
SYS_TOKEN="$(
  RATIO_ODS_L3_URL="$L3_URL" \
  RATIO_ODS_API_KEY="$API_KEY" \
  RATIO_ODS_CLIENT_ID="$SYSTEM_CLIENT_ID" \
  RATIO_ODS_CLIENT_SECRET="$SYSTEM_CLIENT_SECRET" \
  bash "$(dirname "$0")/fetch-l3-token.sh"
)"

echo "Creating operator…" >&2
OP_JSON="$(curl -sf -X POST "${L3_URL}/account/operator" \
  -H "Content-Type: application/json" \
  -H "API-Key: ${API_KEY}" \
  -H "Authorization: Bearer ${SYS_TOKEN}" \
  -d "$(python3 - <<PY
import json
print(json.dumps({
  "login_user_id": "$LOGIN_USER_ID",
  "operator_name": "Ratio PoC Operator",
  "operator_address": "Factory PoC",
  "open_operator_id": "$OPEN_OPERATOR_ID",
  "global_operator_id": "RATIO${SUFFIX}TT000000000",
  "effective_start_date": "2000-01-01",
  "effective_end_date": "9999-12-31",
  "create_password_flag": True,
  "password_temporary_flag": False,
}))
PY
)")"

OPERATOR_ID="$(printf '%s' "$OP_JSON" | python3 -c 'import sys,json; d=json.load(sys.stdin); print((d.get("data") or d).get("operator_id") or "")')"
if [[ -z "$OPERATOR_ID" ]]; then
  echo "FAIL: no operator_id in response" >&2
  exit 1
fi
echo "operator_id=$OPERATOR_ID" >&2

echo "Creating operator client…" >&2
CL_JSON="$(curl -sf -X POST "${L3_URL}/auth/clients" \
  -H "Content-Type: application/json" \
  -H "API-Key: ${API_KEY}" \
  -H "Authorization: Bearer ${SYS_TOKEN}" \
  -d "$(python3 - <<PY
import json
print(json.dumps({
  "flow_type": "client_credentials",
  "client_id": "$CLIENT_ID",
  "name": "Ratio PoC client",
  "description": "client_credentials for AuthZEN Pull",
  "operator_id": "$OPERATOR_ID",
  "open_system_id": "ratio-poc-open-system-$SUFFIX",
}))
PY
)")"

CLIENT_UUID="$(printf '%s' "$CL_JSON" | python3 -c 'import sys,json; d=json.load(sys.stdin); print((d.get("data") or d).get("client_uuid") or "")')"
if [[ -z "$CLIENT_UUID" ]]; then
  echo "FAIL: no client_uuid" >&2
  exit 1
fi

echo "Fetching client secret…" >&2
SEC_JSON="$(curl -sf -X POST "${L3_URL}/auth/clients/secret/${CLIENT_UUID}" \
  -H "API-Key: ${API_KEY}" \
  -H "Authorization: Bearer ${SYS_TOKEN}")"
CLIENT_SECRET="$(printf '%s' "$SEC_JSON" | python3 -c 'import sys,json; d=json.load(sys.stdin); print((d.get("data") or d).get("client_secret") or "")')"
if [[ -z "$CLIENT_SECRET" ]]; then
  echo "FAIL: no client_secret" >&2
  exit 1
fi

umask 077
cat > "$OUT_ENV" <<EOF
# Generated by register-operator.sh — do not commit
RATIO_ODS_L3_URL=$L3_URL
RATIO_ODS_API_KEY=$API_KEY
RATIO_ODS_OPERATOR_ID=$OPERATOR_ID
RATIO_ODS_CLIENT_ID=$CLIENT_ID
RATIO_ODS_CLIENT_SECRET=$CLIENT_SECRET
RATIO_ODS_L2_API_KEY=2dfd3409-ce01-4451-96fa-7e10c9681422y
RATIO_ODS_L2_URL=http://127.0.0.1:8090
RATIO_ODS_USER_ID=ratio-poc
EOF

echo "OK: wrote $OUT_ENV (gitignored)" >&2
echo "OK: operator_id=$OPERATOR_ID client_id=$CLIENT_ID" >&2
echo "Next: source $OUT_ENV && bash poc/scripts/ods/register-openfga-products.sh" >&2
echo "Then:  bash poc/scripts/ods/enable-authzen.sh" >&2
