name: Dependency Submission

on:
  push:
    branches: ["main"]

permissions: {}

jobs:
  dependency-submission:
    name: Submit dependency snapshot
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0  # v7.0.0

      - name: Submit dependency snapshot
        uses: advanced-security/component-detection-dependency-submission-action@31f25a8de68ae5ce2ca274bc28546a78683c15ce  # v0.1.4
